version: 0.1
phases:
  install:
    commands:
      - apt-get update && apt-get -y install python-pip
      - pip install --upgrade python
      - pip install --upgrade awscli
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get -y update
      - apt-get install -y yarn
      - npm i -g lerna@latest yarn@rc
  pre_build:
    commands:
      - yarn config set workspaces-experimental true
      - lerna bootstrap
      - yarn build:core
      - yarn lint 
      - yarn build
      - printenv
      - echo -n "$CODEBUILD_LOG_PATH" > /tmp/build_id.out
      - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
      - printf '{"tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
      - $(aws ecr get-login)
  build:
    commands:
      - docker build --tag "$(cat /tmp/build_tag.out)" .
  post_build:
    commands:
      - docker push "$(cat /tmp/build_tag.out)"
artifacts:
  files: /tmp/build.json
  discard-paths: yes